-- Compute is split by workload so a heavy backfill never slows analysts, and every
-- warehouse has a resource monitor: a runaway query suspends the warehouse instead
-- of burning credits all weekend.
USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS RAW COMMENT = 'Landed data exactly as the lakehouse published it';
CREATE DATABASE IF NOT EXISTS ANALYTICS COMMENT = 'dbt-built models; the only database analysts query';
CREATE DATABASE IF NOT EXISTS GOVERNANCE COMMENT = 'Tags, masking and row access policies, entitlement tables';

-- managed access: grants inside the schema are made centrally, not by object owners
CREATE SCHEMA IF NOT EXISTS RAW.CLAIMS WITH MANAGED ACCESS;

CREATE WAREHOUSE IF NOT EXISTS LOAD_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Lakehouse -> RAW loads';

CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH
    WAREHOUSE_SIZE = SMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    STATEMENT_TIMEOUT_IN_SECONDS = 3600
    COMMENT = 'dbt builds';

CREATE WAREHOUSE IF NOT EXISTS REPORTING_WH
    WAREHOUSE_SIZE = XSMALL
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 3
    SCALING_POLICY = STANDARD
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    STATEMENT_TIMEOUT_IN_SECONDS = 900
    COMMENT = 'BI and analyst queries; multi-cluster absorbs Monday-morning concurrency';

USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS PIPELINE_MONTHLY WITH CREDIT_QUOTA = 100 -- noqa: PRS
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
    ON 75 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND
    ON 110 PERCENT DO SUSPEND_IMMEDIATE;

CREATE RESOURCE MONITOR IF NOT EXISTS REPORTING_MONTHLY WITH CREDIT_QUOTA = 50 -- noqa: PRS
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
    ON 80 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE LOAD_WH SET RESOURCE_MONITOR = PIPELINE_MONTHLY;
ALTER WAREHOUSE TRANSFORM_WH SET RESOURCE_MONITOR = PIPELINE_MONTHLY;
ALTER WAREHOUSE REPORTING_WH SET RESOURCE_MONITOR = REPORTING_MONTHLY;
