-- Functional roles (what a person or service does) inherit access roles (what they
-- may touch). Service users get exactly one functional role; nobody works as SYSADMIN.
--
--   LOADER       writes RAW                      (the platform's publish step)
--   TRANSFORMER  reads RAW, owns ANALYTICS       (dbt)
--   ANALYST      reads ANALYTICS.MARTS only; PII masked; rows limited by line of business
--   PHI_READER   ANALYST plus unmasked PII across all lines of business
--                (care management; granted per person and audited)
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS LOADER;
CREATE ROLE IF NOT EXISTS TRANSFORMER;
CREATE ROLE IF NOT EXISTS ANALYST;
CREATE ROLE IF NOT EXISTS PHI_READER;
CREATE ROLE IF NOT EXISTS GOVERNANCE_ADMIN;

GRANT ROLE ANALYST TO ROLE PHI_READER;
GRANT ROLE LOADER TO ROLE SYSADMIN;
GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;
GRANT ROLE PHI_READER TO ROLE SYSADMIN;
GRANT ROLE GOVERNANCE_ADMIN TO ROLE SYSADMIN;

-- compute
GRANT USAGE ON WAREHOUSE LOAD_WH TO ROLE LOADER;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE TRANSFORMER;
GRANT USAGE ON WAREHOUSE REPORTING_WH TO ROLE ANALYST;

-- RAW: loader writes, transformer reads
GRANT USAGE ON DATABASE RAW TO ROLE LOADER;
GRANT USAGE ON DATABASE RAW TO ROLE TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT ON SCHEMA RAW.CLAIMS TO ROLE LOADER;
GRANT USAGE ON SCHEMA RAW.CLAIMS TO ROLE TRANSFORMER;
GRANT SELECT, INSERT, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA RAW.CLAIMS TO ROLE LOADER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW.CLAIMS TO ROLE TRANSFORMER;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA RAW.CLAIMS TO ROLE LOADER;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA RAW.CLAIMS TO ROLE LOADER;

-- ANALYTICS: dbt builds every layer; analysts read MARTS and nothing else
GRANT USAGE, CREATE SCHEMA ON DATABASE ANALYTICS TO ROLE TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA ANALYTICS.STAGING TO ROLE TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA ANALYTICS.INTERMEDIATE TO ROLE TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA ANALYTICS.SNAPSHOTS TO ROLE TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA ANALYTICS.MARTS TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE ANALYTICS TO ROLE ANALYST;
GRANT USAGE ON SCHEMA ANALYTICS.MARTS TO ROLE ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS.MARTS TO ROLE ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA ANALYTICS.MARTS TO ROLE ANALYST;

-- GOVERNANCE: only the governance admin changes policies; dbt may apply tags
GRANT USAGE, CREATE SCHEMA ON DATABASE GOVERNANCE TO ROLE GOVERNANCE_ADMIN;
GRANT USAGE ON DATABASE GOVERNANCE TO ROLE TRANSFORMER;
-- to tag RAW columns the governance admin must be able to see them
GRANT USAGE ON DATABASE RAW TO ROLE GOVERNANCE_ADMIN;
GRANT USAGE ON SCHEMA RAW.CLAIMS TO ROLE GOVERNANCE_ADMIN;

USE ROLE ACCOUNTADMIN;
GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE GOVERNANCE_ADMIN;
GRANT APPLY ROW ACCESS POLICY ON ACCOUNT TO ROLE GOVERNANCE_ADMIN;
GRANT APPLY TAG ON ACCOUNT TO ROLE GOVERNANCE_ADMIN;
