-- Landing tables for the lakehouse's published Parquet. Column names and types
-- mirror the data contracts (tests/test_snowflake.py fails if they drift apart).
USE ROLE SYSADMIN;

CREATE FILE FORMAT IF NOT EXISTS RAW.CLAIMS.PARQUET_FF TYPE = PARQUET;

CREATE STAGE IF NOT EXISTS RAW.CLAIMS.EXCHANGE
    FILE_FORMAT = RAW.CLAIMS.PARQUET_FF
    COMMENT = 'Internal stage; production points an external stage at the lakehouse export bucket';

CREATE TABLE IF NOT EXISTS RAW.CLAIMS.MEMBERS (
    MEMBER_ID VARCHAR NOT NULL,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    BIRTH_DATE DATE,
    GENDER VARCHAR,
    ZIP3 VARCHAR,
    LINE_OF_BUSINESS VARCHAR,
    COVERAGE_START DATE,
    COVERAGE_END DATE,
    _BATCH_DATE DATE
);

CREATE TABLE IF NOT EXISTS RAW.CLAIMS.PROVIDERS (
    NPI VARCHAR NOT NULL,
    PROVIDER_NAME VARCHAR,
    SPECIALTY VARCHAR,
    STATE VARCHAR,
    IS_FACILITY BOOLEAN
);

CREATE TABLE IF NOT EXISTS RAW.CLAIMS.MEDICAL_CLAIMS_CURRENT (
    CLAIM_ID VARCHAR NOT NULL,
    CLAIM_VERSION INTEGER NOT NULL,
    CLAIM_STATUS VARCHAR,
    CLAIM_TYPE VARCHAR,
    MEMBER_ID VARCHAR,
    BILLING_NPI VARCHAR,
    RENDERING_NPI VARCHAR,
    SERVICE_FROM DATE,
    SERVICE_TO DATE,
    ADMIT_DATE DATE,
    DISCHARGE_DATE DATE,
    PLACE_OF_SERVICE VARCHAR,
    PRIMARY_DX VARCHAR,
    SECONDARY_DX VARCHAR,
    LINE_NUMBER INTEGER NOT NULL,
    PROCEDURE_CODE VARCHAR,
    UNITS INTEGER,
    BILLED_AMOUNT NUMBER(12, 2),
    ALLOWED_AMOUNT NUMBER(12, 2),
    PAID_AMOUNT NUMBER(12, 2),
    PAID_DATE DATE,
    _BATCH_DATE DATE
)
CLUSTER BY (SERVICE_FROM);

CREATE TABLE IF NOT EXISTS RAW.CLAIMS.PHARMACY_CLAIMS (
    RX_CLAIM_ID VARCHAR NOT NULL,
    MEMBER_ID VARCHAR,
    NDC VARCHAR,
    DRUG_NAME VARCHAR,
    FILL_DATE DATE,
    DAYS_SUPPLY INTEGER,
    QUANTITY INTEGER,
    PAID_AMOUNT NUMBER(12, 2),
    PRESCRIBER_NPI VARCHAR,
    _BATCH_DATE DATE
);

CREATE TABLE IF NOT EXISTS RAW.CLAIMS._LOAD_AUDIT (
    TABLE_NAME VARCHAR NOT NULL,
    BATCH_DATE DATE NOT NULL,
    ROW_COUNT INTEGER NOT NULL,
    LOADED_AT TIMESTAMP_NTZ NOT NULL
);
