-- Governance is attached to data, not to queries: PII columns carry a tag, the tag
-- carries a masking policy, so any new column tagged PII is masked with no extra work
-- (dbt applies the same tag to mart columns). Row access limits analysts to the lines
-- of business they are entitled to.
USE ROLE GOVERNANCE_ADMIN;

CREATE SCHEMA IF NOT EXISTS GOVERNANCE.POLICIES WITH MANAGED ACCESS;

CREATE TAG IF NOT EXISTS GOVERNANCE.POLICIES.PII
    ALLOWED_VALUES 'name', 'date_of_birth'
    COMMENT = 'Direct identifiers under HIPAA; masked unless the session has PHI_READER';

CREATE MASKING POLICY IF NOT EXISTS GOVERNANCE.POLICIES.MASK_PII_STRING
AS (val VARCHAR) RETURNS VARCHAR -> -- noqa: LT01
    CASE
        WHEN IS_ROLE_IN_SESSION('PHI_READER') OR IS_ROLE_IN_SESSION('TRANSFORMER') THEN val
        ELSE '***MASKED***'
    END;

-- Dates are generalised to the year rather than nulled, so age-band analysis still works.
CREATE MASKING POLICY IF NOT EXISTS GOVERNANCE.POLICIES.MASK_PII_DATE
AS (val DATE) RETURNS DATE -> -- noqa: LT01
    CASE
        WHEN IS_ROLE_IN_SESSION('PHI_READER') OR IS_ROLE_IN_SESSION('TRANSFORMER') THEN val
        ELSE DATE_FROM_PARTS(YEAR(val), 1, 1)
    END;

ALTER TAG GOVERNANCE.POLICIES.PII SET MASKING POLICY GOVERNANCE.POLICIES.MASK_PII_STRING; -- noqa: PRS
ALTER TAG GOVERNANCE.POLICIES.PII SET MASKING POLICY GOVERNANCE.POLICIES.MASK_PII_DATE; -- noqa: PRS

ALTER TABLE RAW.CLAIMS.MEMBERS MODIFY COLUMN FIRST_NAME SET TAG GOVERNANCE.POLICIES.PII = 'name';
ALTER TABLE RAW.CLAIMS.MEMBERS MODIFY COLUMN LAST_NAME SET TAG GOVERNANCE.POLICIES.PII = 'name';
ALTER TABLE RAW.CLAIMS.MEMBERS MODIFY COLUMN BIRTH_DATE SET TAG GOVERNANCE.POLICIES.PII = 'date_of_birth';

-- entitlement table: which role may see which line of business
CREATE TABLE IF NOT EXISTS GOVERNANCE.POLICIES.LOB_ENTITLEMENTS (
    ROLE_NAME VARCHAR NOT NULL,
    LINE_OF_BUSINESS VARCHAR NOT NULL
);

CREATE ROW ACCESS POLICY IF NOT EXISTS GOVERNANCE.POLICIES.LOB_ROW_ACCESS
AS (lob VARCHAR) RETURNS BOOLEAN ->
    IS_ROLE_IN_SESSION('TRANSFORMER')
    OR IS_ROLE_IN_SESSION('PHI_READER')
    OR EXISTS (
        SELECT 1
        FROM GOVERNANCE.POLICIES.LOB_ENTITLEMENTS AS e
        WHERE IS_ROLE_IN_SESSION(e.ROLE_NAME) AND e.LINE_OF_BUSINESS = lob
    );

GRANT USAGE ON SCHEMA GOVERNANCE.POLICIES TO ROLE TRANSFORMER;
GRANT APPLY ON TAG GOVERNANCE.POLICIES.PII TO ROLE TRANSFORMER;
GRANT APPLY ON ROW ACCESS POLICY GOVERNANCE.POLICIES.LOB_ROW_ACCESS TO ROLE TRANSFORMER;
